### ISSUE TITLE
Standard AWS SSO logins dont work when this extension is installed

### ISSUE THREAD

**Issue by wayne-folkes** [common-fate/granted-browser-extension#3]
When attempting to login to aws using `aws sso login` I get the following error message. This extension assumes that the user will only use `assume` to perform logins. In some situations I need to use the AWS CLI to login via SSO

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/f0705782-a09b-47fe-a663-4ce3089e8e8a">

**Comment by chrnorm** [comment]
@wayne-folkes which situations require the AWS CLI for SSO? Ideally I can help you migrate those use cases to use the Granted CLI, as unfortunately the login flow _has_ to be initiated by Granted for the browser extension to be able to detect the code.

Have you tried the [Granted credential process recipe](https://docs.commonfate.io/granted/recipes/credential-process#:~:text=Granted%20has%20a%20custom%20SSO,be%20prompted%20for%20re%2Dauthentication)?

**Comment by wayne-folkes** [comment]
> @wayne-folkes which situations require the AWS CLI for SSO? Ideally I can help you migrate those use cases to use the Granted CLI, as unfortunately the login flow _has_ to be initiated by Granted for the browser extension to be able to detect the code. The AWS CLI doesn’t have the same browser extension communication feature that Granted has.
> 
> 
> 
> Have you tried the [Granted credential process recipe](https://docs.commonfate.io/granted/recipes/credential-process#:~:text=Granted%20has%20a%20custom%20SSO,be%20prompted%20for%20re%2Dauthentication)?

Yes. After submitting this issue I created a profile that uses the credential process and that worked. My use case was that I am using a Juypter Notebook inside of VS and I need to have my credentials created inside of the notebook so I can make my API calls.

**Comment by chrnorm** [comment]
Fantastic to hear. I’ll close this but feel free to open a new issue if you encounter a use case in future that requires you to use the regular AWS CLI for the SSO login flow.

**Comment by dnrce** [comment]
@chrnorm it doesn't involve the AWS CLI, but another case where this issue is encountered is when using Granted headless (`DefaultBrowser=STDOUT`) on a remote server. So I think the core of this issue is still valid -- the extension currently only works if local Granted is the exclusive thing you are ever authorizing through the device code flow.

Even if it can't prevent phishing entirely, I think a mode of the extension where it automated the button clicks for verified Granted codes but still left them clickable in other cases would be helpful. By automating the common case, the un-automated cases would be left to feel atypical, and users would be less conditioned to click through them without paying attention.
